name: Build Kernel
on:
  workflow_dispatch:
    inputs:
      KBUILD_USER:
        description: Kbuild user
        default: 'rsuntk'
        required: true
      SETUP_KSU:
        description: KernelSU support (optional)
        type: boolean
      UPLOAD_TO_TG:
        description: Upload to Telegram
        type: boolean
        
jobs:
  build:
    runs-on: ubuntu-latest
    environment: uploadTelegram
    steps:
    - uses: actions/checkout@v4
      with:
        path: kernel_root
        show-progress: false
        fetch-depth: 1
        
    - name: Prepare dependencies
      run: |
        sudo apt update -y
        sudo apt install bc cpio flex bison aptitude git python-is-python3 libc6 libc6-dev tar perl curl lz4 -y
        sudo aptitude install libssl-dev -y
        
    - name: Fetch toolchains
      run: |
        mkdir toolchains
        cd toolchains
        git clone --depth=1 https://gitlab.com/Rissu-Projekt/toolchains/clang-toolchains -b clang-r383902 clang-11
        git clone https://gitlab.com/Rissu-Projekt/toolchains/aarch64-linux-android.git --depth=1 google
      working-directory: kernel_root

    - name: Prepare timezone fix
      run: |
        sudo rm /etc/localtime
        sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
        
    - name: Build kernel
      id: buildKernel
      run: |
        export PATH=$(pwd)/toolchains/clang-11/bin:$PATH
        export CROSS_COMPILE=$(pwd)/toolchains/google/bin/aarch64-linux-android-
        export CLANG_TRIPLE=aarch64-linux-gnu-
        export KBUILD_BUILD_HOST="rsuntk_orgs"
        export KBUILD_BUILD_USER="${{ github.event.inputs.KBUILD_USER }}"
        export BUILD_START=$(date)
        export IS_CI=true
        export DEVICE=A235F
        
        if [[ "${{ github.event.inputs.SETUP_KSU }}" = "true" ]]; then 
          export KERNELSU=true
        fi
        
        bash $(pwd)/build.sh kernel --jobs $(nproc --all) rsuntk_defconfig
        
        echo ""
        echo "===================================================="
        strings out/arch/arm64/boot/Image | grep "Linux version"
        echo "===================================================="
        mv out/.config out/build_config.txt
        gitsha1=$(git rev-parse --short HEAD)
        buildDetails="`make kernelversion`_`echo $gitsha1`-`date +'%Y%m%d%H%M%S'`" && echo "buildDetails=$buildDetails" >> $GITHUB_OUTPUT
      working-directory: kernel_root
      
    - name: Upload config
      uses: actions/upload-artifact@v4
      with:
        name: Config-${{ steps.buildKernel.outputs.buildDetails }}
        path: kernel_root/out/build_config.txt
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build-${{ steps.buildKernel.outputs.buildDetails }}
        path: |
          kernel_root/out/arch/arm64/boot/*
          
    - name: Upload AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3-${{ steps.buildKernel.outputs.buildDetails }}
        path: kernel_root/AnyKernel3/*
        compression-level: 9
        
    - name: Upload to Telegram
      if: github.event.inputs.UPLOAD_TO_TG == 'true'
      env:
        CHAT_ID: ${{ secrets.CHAT_ID }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        TITLE: "Galaxy A23 Kernel"
      run: |
        if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
          ZIP=$(find `pwd` -name "*.zip")
          bash $(pwd)/scripts/rsuntkbot.sh $ZIP "`cat buildDetails.txt`"
        fi
      working-directory: kernel_root